language: ruby
cache: bundler
rvm:
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
services:
  - postgresql
addons:
  chrome: stable
  postgresql: "9.6"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq -y graphicsmagick
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - gem update bundler
  - yarn install
