sudo: false
language: ruby
rvm:
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
addons:
  postgresql: "9.6"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - graphicsmagick
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
before_install:
  - gem update bundler
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - rails db:create
  - rails db:migrate
