sudo: false
language: ruby
rvm:
  - 2.4.1
  - 2.4.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: 2.4.2
    - rvm: ruby-head
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
addons:
  postgresql: "9.6"
  apt:
    packages:
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - graphicsmagick
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
before_install:
  - gem update bundler
  - yarn install
env:
  - API_RETURN_ROOT=https://example.com
