language: ruby
cache: bundler
rvm:
  - 2.4.1
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
addons:
  chrome: stable
services:
  - postgresql
before_install:
  - sudo apt-get update
  - sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
  - sudo apt-get install -qq graphicsmagick
  - gem update bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
